### ISSUE TITLE
tfe_workspace table doesn't populate the vcs_repo column

### ISSUE THREAD

**Issue by mildmojo** [turbot/steampipe-plugin-tfe#18]
**Describe the bug**
When I query my TFE account with something like 700+ VCS-connected workspaces, most fields are populated, but the `vcs_repo` column is always null.

**Steampipe version (`steampipe -v`)**
v0.16.1

**Plugin version (`steampipe plugin list`)**
v0.3.1

**To reproduce**

In a TFE account with VCS-connected workspaces, run this query:

```
select 
	count(*) as count
from
	tfe.tfe_workspace
where
	vcs_repo is not null
```

The query returns a count of 0.

**Expected behavior**

The count from that query should be the number of VCS-connected workspaces in your TFE account.

**Comment by misraved** [comment]
Welcome to Steampipe @mildmojo and thanks for reporting this issue.

We will try to reproduce this bug and push for a fix shortly. Thanks 👍.
