### ISSUE TITLE
Add table tfe_project

### ISSUE THREAD

**Issue by edebrye** [turbot/steampipe-plugin-tfe#41]
Hello, 

I would like to be able to get a workspace's project attribute. 

I believe a new table `tfe_project` is required, as well as an attribute `project` in the table `tfe_workspace` referencing the `tfe_project` id.

As a prerequisite, the go-tfe package needs to be upgraded to its latest version since version 0.17 does not deal with projects.

Tasks:
- [x] upgrade go-tfe >= 1.40
- [x] add table `tfe_project`
- [x] add attribute `project` ( or `project_id` ?) in the table `tfe_workspace`

I would be happy to contribute.

**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

- Go SDK Project client : https://pkg.go.dev/github.com/hashicorp/go-tfe#Projects
- TFE documentation about projects : https://developer.hashicorp.com/terraform/cloud-docs/workspaces/organize-workspaces-with-projects
- TFE API about projects : https://developer.hashicorp.com/terraform/cloud-docs/api-docs/projects

**Comment by cbruno10** [comment]
Hi @edebrye , thanks for opening this issue!

We'd love any contributions in this plugin (upgrading the SDK, adding a new table, columns, etc.).

For upgrading the SDK, do you know if there are any breaking changes between our current version and the latest version of `go-tfe`?

**Comment by edebrye** [comment]
I think there is not much, some options for list calls have changed from a string to a list of string, and the option object for these calls have to be passed with a pointer instead of a reference.

**Comment by edebrye** [comment]
I would be interested in opening a PR, should I fork the repo ?

**Comment by e-gineer** [comment]
Yes thanks @edebrye, forking into your user account is the usual approach and then just open a PR back when ready :-)

**Comment by edebrye** [comment]
Hello ! Is someone available for a review on the PR please :) ?

I also included a documentation according to #43.

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-plugin-tfe/pull/42

Thanks @edebrye for the contribution 🎉 !!
